export const localidades = [
  { key: 0, value: "" },
  { key: 1, value: "Capital Federal" },
  { key: 2, value: "Buenos Aires" },
  { key: 3, value: "Misiones" },
  { key: 4, value: "Cordoba" },
  { key: 5, value: "Entre Rios" },
  { key: 6, value: "La Pampa" },
  { key: 7, value: "Tierra del Fuego" },
  { key: 8, value: "Santa Fe" },
  { key: 9, value: "Chaco" },
  { key: 10, value: "Mendoza" },
  { key: 11, value: "Salta" },
  { key: 12, value: "Tucuman" },
  { key: 13, value: "Jujuy" },
  { key: 14, value: "Corrientes" },
  { key: 15, value: "Rio Negro" },
  { key: 16, value: "Neuquen" },
  { key: 17, value: "San Juan" },
  { key: 18, value: "Chubut" },
  { key: 19, value: "San Luis" },
  { key: 20, value: "Formosa" },
  { key: 21, value: "Formosa" },
  { key: 22, value: "Santa Cruz" },
  { key: 23, value: "La Rioja" },
  { key: 24, value: "Santiago del Estero" },
  { key: 25, value: "Catamarca" },
];
